# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import service_pb2 as service__pb2


class IsolatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireIsolate = channel.stream_stream(
                '/isolator.Isolator/AcquireIsolate',
                request_serializer=service__pb2.IsolateRequest.SerializeToString,
                response_deserializer=service__pb2.IsolateResponse.FromString,
                )
        self.KillIsolates = channel.unary_unary(
                '/isolator.Isolator/KillIsolates',
                request_serializer=service__pb2.KillIsolatesRequest.SerializeToString,
                response_deserializer=service__pb2.KillIsolatesResponse.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/isolator.Isolator/GetStatus',
                request_serializer=service__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=service__pb2.GetStatusResponse.FromString,
                )
        self.Drain = channel.unary_unary(
                '/isolator.Isolator/Drain',
                request_serializer=service__pb2.DrainRequest.SerializeToString,
                response_deserializer=service__pb2.DrainResponse.FromString,
                )
        self.Kill = channel.unary_unary(
                '/isolator.Isolator/Kill',
                request_serializer=service__pb2.KillRequest.SerializeToString,
                response_deserializer=service__pb2.KillResponse.FromString,
                )


class IsolatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AcquireIsolate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillIsolates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IsolatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireIsolate': grpc.stream_stream_rpc_method_handler(
                    servicer.AcquireIsolate,
                    request_deserializer=service__pb2.IsolateRequest.FromString,
                    response_serializer=service__pb2.IsolateResponse.SerializeToString,
            ),
            'KillIsolates': grpc.unary_unary_rpc_method_handler(
                    servicer.KillIsolates,
                    request_deserializer=service__pb2.KillIsolatesRequest.FromString,
                    response_serializer=service__pb2.KillIsolatesResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=service__pb2.GetStatusRequest.FromString,
                    response_serializer=service__pb2.GetStatusResponse.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=service__pb2.DrainRequest.FromString,
                    response_serializer=service__pb2.DrainResponse.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=service__pb2.KillRequest.FromString,
                    response_serializer=service__pb2.KillResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isolator.Isolator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Isolator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcquireIsolate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/isolator.Isolator/AcquireIsolate',
            service__pb2.IsolateRequest.SerializeToString,
            service__pb2.IsolateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def KillIsolates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/isolator.Isolator/KillIsolates',
            service__pb2.KillIsolatesRequest.SerializeToString,
            service__pb2.KillIsolatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/isolator.Isolator/GetStatus',
            service__pb2.GetStatusRequest.SerializeToString,
            service__pb2.GetStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/isolator.Isolator/Drain',
            service__pb2.DrainRequest.SerializeToString,
            service__pb2.DrainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/isolator.Isolator/Kill',
            service__pb2.KillRequest.SerializeToString,
            service__pb2.KillResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
