# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import service_pb2


class IsolatorBase(abc.ABC):

    @abc.abstractmethod
    async def AcquireIsolate(self, stream: 'grpclib.server.Stream[service_pb2.IsolateRequest, service_pb2.IsolateResponse]') -> None:
        pass

    @abc.abstractmethod
    async def KillIsolates(self, stream: 'grpclib.server.Stream[service_pb2.KillIsolatesRequest, service_pb2.KillIsolatesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetStatus(self, stream: 'grpclib.server.Stream[service_pb2.GetStatusRequest, service_pb2.GetStatusResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Drain(self, stream: 'grpclib.server.Stream[service_pb2.DrainRequest, service_pb2.DrainResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Kill(self, stream: 'grpclib.server.Stream[service_pb2.KillRequest, service_pb2.KillResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/isolator.Isolator/AcquireIsolate': grpclib.const.Handler(
                self.AcquireIsolate,
                grpclib.const.Cardinality.STREAM_STREAM,
                service_pb2.IsolateRequest,
                service_pb2.IsolateResponse,
            ),
            '/isolator.Isolator/KillIsolates': grpclib.const.Handler(
                self.KillIsolates,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.KillIsolatesRequest,
                service_pb2.KillIsolatesResponse,
            ),
            '/isolator.Isolator/GetStatus': grpclib.const.Handler(
                self.GetStatus,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.GetStatusRequest,
                service_pb2.GetStatusResponse,
            ),
            '/isolator.Isolator/Drain': grpclib.const.Handler(
                self.Drain,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.DrainRequest,
                service_pb2.DrainResponse,
            ),
            '/isolator.Isolator/Kill': grpclib.const.Handler(
                self.Kill,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.KillRequest,
                service_pb2.KillResponse,
            ),
        }


class IsolatorStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.AcquireIsolate = grpclib.client.StreamStreamMethod(
            channel,
            '/isolator.Isolator/AcquireIsolate',
            service_pb2.IsolateRequest,
            service_pb2.IsolateResponse,
        )
        self.KillIsolates = grpclib.client.UnaryUnaryMethod(
            channel,
            '/isolator.Isolator/KillIsolates',
            service_pb2.KillIsolatesRequest,
            service_pb2.KillIsolatesResponse,
        )
        self.GetStatus = grpclib.client.UnaryUnaryMethod(
            channel,
            '/isolator.Isolator/GetStatus',
            service_pb2.GetStatusRequest,
            service_pb2.GetStatusResponse,
        )
        self.Drain = grpclib.client.UnaryUnaryMethod(
            channel,
            '/isolator.Isolator/Drain',
            service_pb2.DrainRequest,
            service_pb2.DrainResponse,
        )
        self.Kill = grpclib.client.UnaryUnaryMethod(
            channel,
            '/isolator.Isolator/Kill',
            service_pb2.KillRequest,
            service_pb2.KillResponse,
        )
