# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backups.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backups.proto',
  package='backups',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbackups.proto\x12\x07\x62\x61\x63kups\"C\n\rCreateRequest\x12\x10\n\x08guild_id\x18\x01 \x01(\t\x12\x0f\n\x07options\x18\x02 \x03(\t\x12\x0f\n\x07\x63hatlog\x18\x03 \x01(\r\"\x1d\n\x0b\x43reateReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"}\n\x0bLoadRequest\x12\x11\n\tbackup_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08guild_id\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65\x63ryption_key\x18\x04 \x01(\t\x12\x0f\n\x07options\x18\x05 \x03(\t\x12\x0f\n\x07\x63hatlog\x18\x06 \x01(\r\"\x1b\n\tLoadReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"%\n\x11LoadStatusRequest\x12\x10\n\x08guild_id\x18\x01 \x01(\t\"!\n\x0fLoadStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"%\n\x11\x43\x61ncelLoadRequest\x12\x10\n\x08guild_id\x18\x01 \x01(\t\"\x11\n\x0f\x43\x61ncelLoadReply2\x87\x02\n\x07\x42\x61\x63kups\x12:\n\x06\x43reate\x12\x16.backups.CreateRequest\x1a\x14.backups.CreateReply\"\x00\x30\x01\x12\x34\n\x04Load\x12\x14.backups.LoadRequest\x1a\x12.backups.LoadReply\"\x00\x30\x01\x12\x44\n\nLoadStatus\x12\x1a.backups.LoadStatusRequest\x1a\x18.backups.LoadStatusReply\"\x00\x12\x44\n\nCancelLoad\x12\x1a.backups.CancelLoadRequest\x1a\x18.backups.CancelLoadReply\"\x00\x62\x06proto3'
)




_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='backups.CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='backups.CreateRequest.guild_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='options', full_name='backups.CreateRequest.options', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chatlog', full_name='backups.CreateRequest.chatlog', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=93,
)


_CREATEREPLY = _descriptor.Descriptor(
  name='CreateReply',
  full_name='backups.CreateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='backups.CreateReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=124,
)


_LOADREQUEST = _descriptor.Descriptor(
  name='LoadRequest',
  full_name='backups.LoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='backup_id', full_name='backups.LoadRequest.backup_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='backups.LoadRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='backups.LoadRequest.guild_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='decryption_key', full_name='backups.LoadRequest.decryption_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='options', full_name='backups.LoadRequest.options', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chatlog', full_name='backups.LoadRequest.chatlog', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=251,
)


_LOADREPLY = _descriptor.Descriptor(
  name='LoadReply',
  full_name='backups.LoadReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='backups.LoadReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=280,
)


_LOADSTATUSREQUEST = _descriptor.Descriptor(
  name='LoadStatusRequest',
  full_name='backups.LoadStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='backups.LoadStatusRequest.guild_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=319,
)


_LOADSTATUSREPLY = _descriptor.Descriptor(
  name='LoadStatusReply',
  full_name='backups.LoadStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='backups.LoadStatusReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=354,
)


_CANCELLOADREQUEST = _descriptor.Descriptor(
  name='CancelLoadRequest',
  full_name='backups.CancelLoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='backups.CancelLoadRequest.guild_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=393,
)


_CANCELLOADREPLY = _descriptor.Descriptor(
  name='CancelLoadReply',
  full_name='backups.CancelLoadReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=412,
)

DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['CreateReply'] = _CREATEREPLY
DESCRIPTOR.message_types_by_name['LoadRequest'] = _LOADREQUEST
DESCRIPTOR.message_types_by_name['LoadReply'] = _LOADREPLY
DESCRIPTOR.message_types_by_name['LoadStatusRequest'] = _LOADSTATUSREQUEST
DESCRIPTOR.message_types_by_name['LoadStatusReply'] = _LOADSTATUSREPLY
DESCRIPTOR.message_types_by_name['CancelLoadRequest'] = _CANCELLOADREQUEST
DESCRIPTOR.message_types_by_name['CancelLoadReply'] = _CANCELLOADREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREQUEST,
  '__module__' : 'backups_pb2'
  # @@protoc_insertion_point(class_scope:backups.CreateRequest)
  })
_sym_db.RegisterMessage(CreateRequest)

CreateReply = _reflection.GeneratedProtocolMessageType('CreateReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREPLY,
  '__module__' : 'backups_pb2'
  # @@protoc_insertion_point(class_scope:backups.CreateReply)
  })
_sym_db.RegisterMessage(CreateReply)

LoadRequest = _reflection.GeneratedProtocolMessageType('LoadRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADREQUEST,
  '__module__' : 'backups_pb2'
  # @@protoc_insertion_point(class_scope:backups.LoadRequest)
  })
_sym_db.RegisterMessage(LoadRequest)

LoadReply = _reflection.GeneratedProtocolMessageType('LoadReply', (_message.Message,), {
  'DESCRIPTOR' : _LOADREPLY,
  '__module__' : 'backups_pb2'
  # @@protoc_insertion_point(class_scope:backups.LoadReply)
  })
_sym_db.RegisterMessage(LoadReply)

LoadStatusRequest = _reflection.GeneratedProtocolMessageType('LoadStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADSTATUSREQUEST,
  '__module__' : 'backups_pb2'
  # @@protoc_insertion_point(class_scope:backups.LoadStatusRequest)
  })
_sym_db.RegisterMessage(LoadStatusRequest)

LoadStatusReply = _reflection.GeneratedProtocolMessageType('LoadStatusReply', (_message.Message,), {
  'DESCRIPTOR' : _LOADSTATUSREPLY,
  '__module__' : 'backups_pb2'
  # @@protoc_insertion_point(class_scope:backups.LoadStatusReply)
  })
_sym_db.RegisterMessage(LoadStatusReply)

CancelLoadRequest = _reflection.GeneratedProtocolMessageType('CancelLoadRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANCELLOADREQUEST,
  '__module__' : 'backups_pb2'
  # @@protoc_insertion_point(class_scope:backups.CancelLoadRequest)
  })
_sym_db.RegisterMessage(CancelLoadRequest)

CancelLoadReply = _reflection.GeneratedProtocolMessageType('CancelLoadReply', (_message.Message,), {
  'DESCRIPTOR' : _CANCELLOADREPLY,
  '__module__' : 'backups_pb2'
  # @@protoc_insertion_point(class_scope:backups.CancelLoadReply)
  })
_sym_db.RegisterMessage(CancelLoadReply)



_BACKUPS = _descriptor.ServiceDescriptor(
  name='Backups',
  full_name='backups.Backups',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=415,
  serialized_end=678,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='backups.Backups.Create',
    index=0,
    containing_service=None,
    input_type=_CREATEREQUEST,
    output_type=_CREATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Load',
    full_name='backups.Backups.Load',
    index=1,
    containing_service=None,
    input_type=_LOADREQUEST,
    output_type=_LOADREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoadStatus',
    full_name='backups.Backups.LoadStatus',
    index=2,
    containing_service=None,
    input_type=_LOADSTATUSREQUEST,
    output_type=_LOADSTATUSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CancelLoad',
    full_name='backups.Backups.CancelLoad',
    index=3,
    containing_service=None,
    input_type=_CANCELLOADREQUEST,
    output_type=_CANCELLOADREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKUPS)

DESCRIPTOR.services_by_name['Backups'] = _BACKUPS

# @@protoc_insertion_point(module_scope)
