# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatlogs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatlogs.proto',
  package='chatlogs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63hatlogs.proto\x12\x08\x63hatlogs\"#\n\rCreateRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\t\"\r\n\x0b\x43reateReply\"!\n\x0bLoadRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\t\"\x0b\n\tLoadReply2\x80\x01\n\x08\x43hatlogs\x12<\n\x06\x43reate\x12\x17.chatlogs.CreateRequest\x1a\x15.chatlogs.CreateReply\"\x00\x30\x01\x12\x36\n\x04Load\x12\x15.chatlogs.LoadRequest\x1a\x13.chatlogs.LoadReply\"\x00\x30\x01\x62\x06proto3'
)




_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='chatlogs.CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='chatlogs.CreateRequest.channel_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=63,
)


_CREATEREPLY = _descriptor.Descriptor(
  name='CreateReply',
  full_name='chatlogs.CreateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=78,
)


_LOADREQUEST = _descriptor.Descriptor(
  name='LoadRequest',
  full_name='chatlogs.LoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='chatlogs.LoadRequest.channel_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=113,
)


_LOADREPLY = _descriptor.Descriptor(
  name='LoadReply',
  full_name='chatlogs.LoadReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['CreateReply'] = _CREATEREPLY
DESCRIPTOR.message_types_by_name['LoadRequest'] = _LOADREQUEST
DESCRIPTOR.message_types_by_name['LoadReply'] = _LOADREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREQUEST,
  '__module__' : 'chatlogs_pb2'
  # @@protoc_insertion_point(class_scope:chatlogs.CreateRequest)
  })
_sym_db.RegisterMessage(CreateRequest)

CreateReply = _reflection.GeneratedProtocolMessageType('CreateReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREPLY,
  '__module__' : 'chatlogs_pb2'
  # @@protoc_insertion_point(class_scope:chatlogs.CreateReply)
  })
_sym_db.RegisterMessage(CreateReply)

LoadRequest = _reflection.GeneratedProtocolMessageType('LoadRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADREQUEST,
  '__module__' : 'chatlogs_pb2'
  # @@protoc_insertion_point(class_scope:chatlogs.LoadRequest)
  })
_sym_db.RegisterMessage(LoadRequest)

LoadReply = _reflection.GeneratedProtocolMessageType('LoadReply', (_message.Message,), {
  'DESCRIPTOR' : _LOADREPLY,
  '__module__' : 'chatlogs_pb2'
  # @@protoc_insertion_point(class_scope:chatlogs.LoadReply)
  })
_sym_db.RegisterMessage(LoadReply)



_CHATLOGS = _descriptor.ServiceDescriptor(
  name='Chatlogs',
  full_name='chatlogs.Chatlogs',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=129,
  serialized_end=257,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='chatlogs.Chatlogs.Create',
    index=0,
    containing_service=None,
    input_type=_CREATEREQUEST,
    output_type=_CREATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Load',
    full_name='chatlogs.Chatlogs.Load',
    index=1,
    containing_service=None,
    input_type=_LOADREQUEST,
    output_type=_LOADREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATLOGS)

DESCRIPTOR.services_by_name['Chatlogs'] = _CHATLOGS

# @@protoc_insertion_point(module_scope)
