# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutations.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import backups_pb2 as backups__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mutations.proto',
  package='mutations',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmutations.proto\x12\tmutations\x1a\rbackups.proto\"L\n\x08Mutation\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x11\n\ttarget_id\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"h\n\x11MutationContainer\x12+\n\x0estarting_point\x18\x01 \x01(\x0b\x32\x13.backups.BackupData\x12&\n\tmutations\x18\x02 \x03(\x0b\x32\x13.mutations.Mutation\"`\n\x18\x44iscoverMutationsRequest\x12\"\n\x05start\x18\x01 \x01(\x0b\x32\x13.backups.BackupData\x12 \n\x03\x65nd\x18\x02 \x01(\x0b\x32\x13.backups.BackupData\"Q\n\x15\x41pplyMutationsRequest\x12\x10\n\x08guild_id\x18\x01 \x01(\t\x12&\n\tmutations\x18\x02 \x03(\x0b\x32\x13.mutations.Mutation\"\x18\n\x16\x41pplyMutationsResponse2\xa9\x03\n\x07\x42\x61\x63kups\x12P\n\x10\x46lattenMutations\x12\x1c.mutations.MutationContainer\x1a\x1c.mutations.MutationContainer\"\x00\x12P\n\x10ReverseMutations\x12\x1c.mutations.MutationContainer\x1a\x1c.mutations.MutationContainer\"\x00\x12X\n\x11\x44iscoverMutations\x12#.mutations.DiscoverMutationsRequest\x1a\x1c.mutations.MutationContainer\"\x00\x12\x45\n\x0eMergeMutations\x12\x1c.mutations.MutationContainer\x1a\x13.backups.BackupData\"\x00\x12Y\n\x0e\x41pplyMutations\x12 .mutations.ApplyMutationsRequest\x1a!.mutations.ApplyMutationsResponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[backups__pb2.DESCRIPTOR,])




_MUTATION = _descriptor.Descriptor(
  name='Mutation',
  full_name='mutations.Mutation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mutations.Mutation.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mutations.Mutation.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_id', full_name='mutations.Mutation.target_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='mutations.Mutation.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=121,
)


_MUTATIONCONTAINER = _descriptor.Descriptor(
  name='MutationContainer',
  full_name='mutations.MutationContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='starting_point', full_name='mutations.MutationContainer.starting_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mutations', full_name='mutations.MutationContainer.mutations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=227,
)


_DISCOVERMUTATIONSREQUEST = _descriptor.Descriptor(
  name='DiscoverMutationsRequest',
  full_name='mutations.DiscoverMutationsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='mutations.DiscoverMutationsRequest.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='mutations.DiscoverMutationsRequest.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=325,
)


_APPLYMUTATIONSREQUEST = _descriptor.Descriptor(
  name='ApplyMutationsRequest',
  full_name='mutations.ApplyMutationsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='mutations.ApplyMutationsRequest.guild_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mutations', full_name='mutations.ApplyMutationsRequest.mutations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=408,
)


_APPLYMUTATIONSRESPONSE = _descriptor.Descriptor(
  name='ApplyMutationsResponse',
  full_name='mutations.ApplyMutationsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=434,
)

_MUTATIONCONTAINER.fields_by_name['starting_point'].message_type = backups__pb2._BACKUPDATA
_MUTATIONCONTAINER.fields_by_name['mutations'].message_type = _MUTATION
_DISCOVERMUTATIONSREQUEST.fields_by_name['start'].message_type = backups__pb2._BACKUPDATA
_DISCOVERMUTATIONSREQUEST.fields_by_name['end'].message_type = backups__pb2._BACKUPDATA
_APPLYMUTATIONSREQUEST.fields_by_name['mutations'].message_type = _MUTATION
DESCRIPTOR.message_types_by_name['Mutation'] = _MUTATION
DESCRIPTOR.message_types_by_name['MutationContainer'] = _MUTATIONCONTAINER
DESCRIPTOR.message_types_by_name['DiscoverMutationsRequest'] = _DISCOVERMUTATIONSREQUEST
DESCRIPTOR.message_types_by_name['ApplyMutationsRequest'] = _APPLYMUTATIONSREQUEST
DESCRIPTOR.message_types_by_name['ApplyMutationsResponse'] = _APPLYMUTATIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mutation = _reflection.GeneratedProtocolMessageType('Mutation', (_message.Message,), {
  'DESCRIPTOR' : _MUTATION,
  '__module__' : 'mutations_pb2'
  # @@protoc_insertion_point(class_scope:mutations.Mutation)
  })
_sym_db.RegisterMessage(Mutation)

MutationContainer = _reflection.GeneratedProtocolMessageType('MutationContainer', (_message.Message,), {
  'DESCRIPTOR' : _MUTATIONCONTAINER,
  '__module__' : 'mutations_pb2'
  # @@protoc_insertion_point(class_scope:mutations.MutationContainer)
  })
_sym_db.RegisterMessage(MutationContainer)

DiscoverMutationsRequest = _reflection.GeneratedProtocolMessageType('DiscoverMutationsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERMUTATIONSREQUEST,
  '__module__' : 'mutations_pb2'
  # @@protoc_insertion_point(class_scope:mutations.DiscoverMutationsRequest)
  })
_sym_db.RegisterMessage(DiscoverMutationsRequest)

ApplyMutationsRequest = _reflection.GeneratedProtocolMessageType('ApplyMutationsRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPLYMUTATIONSREQUEST,
  '__module__' : 'mutations_pb2'
  # @@protoc_insertion_point(class_scope:mutations.ApplyMutationsRequest)
  })
_sym_db.RegisterMessage(ApplyMutationsRequest)

ApplyMutationsResponse = _reflection.GeneratedProtocolMessageType('ApplyMutationsResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPLYMUTATIONSRESPONSE,
  '__module__' : 'mutations_pb2'
  # @@protoc_insertion_point(class_scope:mutations.ApplyMutationsResponse)
  })
_sym_db.RegisterMessage(ApplyMutationsResponse)



_BACKUPS = _descriptor.ServiceDescriptor(
  name='Backups',
  full_name='mutations.Backups',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=437,
  serialized_end=862,
  methods=[
  _descriptor.MethodDescriptor(
    name='FlattenMutations',
    full_name='mutations.Backups.FlattenMutations',
    index=0,
    containing_service=None,
    input_type=_MUTATIONCONTAINER,
    output_type=_MUTATIONCONTAINER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReverseMutations',
    full_name='mutations.Backups.ReverseMutations',
    index=1,
    containing_service=None,
    input_type=_MUTATIONCONTAINER,
    output_type=_MUTATIONCONTAINER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DiscoverMutations',
    full_name='mutations.Backups.DiscoverMutations',
    index=2,
    containing_service=None,
    input_type=_DISCOVERMUTATIONSREQUEST,
    output_type=_MUTATIONCONTAINER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MergeMutations',
    full_name='mutations.Backups.MergeMutations',
    index=3,
    containing_service=None,
    input_type=_MUTATIONCONTAINER,
    output_type=backups__pb2._BACKUPDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ApplyMutations',
    full_name='mutations.Backups.ApplyMutations',
    index=4,
    containing_service=None,
    input_type=_APPLYMUTATIONSREQUEST,
    output_type=_APPLYMUTATIONSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKUPS)

DESCRIPTOR.services_by_name['Backups'] = _BACKUPS

# @@protoc_insertion_point(module_scope)
