# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import backups_pb2 as backups__pb2
from . import mutations_pb2 as mutations__pb2


class BackupsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FlattenMutations = channel.unary_unary(
                '/mutations.Backups/FlattenMutations',
                request_serializer=mutations__pb2.MutationContainer.SerializeToString,
                response_deserializer=mutations__pb2.MutationContainer.FromString,
                )
        self.ReverseMutations = channel.unary_unary(
                '/mutations.Backups/ReverseMutations',
                request_serializer=mutations__pb2.MutationContainer.SerializeToString,
                response_deserializer=mutations__pb2.MutationContainer.FromString,
                )
        self.DiscoverMutations = channel.unary_unary(
                '/mutations.Backups/DiscoverMutations',
                request_serializer=mutations__pb2.DiscoverMutationsRequest.SerializeToString,
                response_deserializer=mutations__pb2.MutationContainer.FromString,
                )
        self.MergeMutations = channel.unary_unary(
                '/mutations.Backups/MergeMutations',
                request_serializer=mutations__pb2.MutationContainer.SerializeToString,
                response_deserializer=backups__pb2.BackupData.FromString,
                )
        self.ApplyMutations = channel.unary_stream(
                '/mutations.Backups/ApplyMutations',
                request_serializer=mutations__pb2.ApplyMutationsRequest.SerializeToString,
                response_deserializer=mutations__pb2.ApplyMutationsResponse.FromString,
                )


class BackupsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FlattenMutations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverseMutations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverMutations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeMutations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyMutations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackupsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FlattenMutations': grpc.unary_unary_rpc_method_handler(
                    servicer.FlattenMutations,
                    request_deserializer=mutations__pb2.MutationContainer.FromString,
                    response_serializer=mutations__pb2.MutationContainer.SerializeToString,
            ),
            'ReverseMutations': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseMutations,
                    request_deserializer=mutations__pb2.MutationContainer.FromString,
                    response_serializer=mutations__pb2.MutationContainer.SerializeToString,
            ),
            'DiscoverMutations': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverMutations,
                    request_deserializer=mutations__pb2.DiscoverMutationsRequest.FromString,
                    response_serializer=mutations__pb2.MutationContainer.SerializeToString,
            ),
            'MergeMutations': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeMutations,
                    request_deserializer=mutations__pb2.MutationContainer.FromString,
                    response_serializer=backups__pb2.BackupData.SerializeToString,
            ),
            'ApplyMutations': grpc.unary_stream_rpc_method_handler(
                    servicer.ApplyMutations,
                    request_deserializer=mutations__pb2.ApplyMutationsRequest.FromString,
                    response_serializer=mutations__pb2.ApplyMutationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mutations.Backups', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Backups(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FlattenMutations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mutations.Backups/FlattenMutations',
            mutations__pb2.MutationContainer.SerializeToString,
            mutations__pb2.MutationContainer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReverseMutations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mutations.Backups/ReverseMutations',
            mutations__pb2.MutationContainer.SerializeToString,
            mutations__pb2.MutationContainer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DiscoverMutations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mutations.Backups/DiscoverMutations',
            mutations__pb2.DiscoverMutationsRequest.SerializeToString,
            mutations__pb2.MutationContainer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MergeMutations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mutations.Backups/MergeMutations',
            mutations__pb2.MutationContainer.SerializeToString,
            backups__pb2.BackupData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyMutations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mutations.Backups/ApplyMutations',
            mutations__pb2.ApplyMutationsRequest.SerializeToString,
            mutations__pb2.ApplyMutationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
