syntax = "proto3";

import "backups.proto";

package mutations;

message Mutation {
  uint32 type = 1;
  uint64 timestamp = 2;
  string target_id = 3;
  bytes data = 4;
}

message MutationContainer {
  backups.BackupData starting_point = 1;
  repeated Mutation mutations = 2;
}

message DiscoverMutationsRequest {
  backups.BackupData start = 1;
  backups.BackupData end = 2;
}

message ApplyMutationsRequest {
  string guild_id = 1;
  repeated Mutation mutations = 2;
}

message ApplyMutationsResponse {}

service Backups {
  rpc FlattenMutations(MutationContainer) returns (MutationContainer) {}
  rpc ReverseMutations(MutationContainer) returns (MutationContainer) {}
  rpc DiscoverMutations(DiscoverMutationsRequest) returns (MutationContainer) {}
  rpc MergeMutations(MutationContainer) returns (backups.BackupData) {}
  rpc ApplyMutations(ApplyMutationsRequest) returns (stream ApplyMutationsResponse) {}
}
